network:
  version: 2
  renderer: networkd
  wifis:
    wlan0:
      access-points:
        <wifi_network_name>:
          password: "<wifi_password>"
      addresses:
        - <static_ip_address>
      routes:
        - to: default
          via: <router_ip_address>
      nameservers:
          addresses: [<dns_servers>]

